---
collections:
  # - name: aap.platform_on_ocp
  - name: ansible.controller
    # For infra.aap_configuration
    # version: '>=4.6.0'
    # For infra.controller_configuration
    version: '>=4.5.0,<4.6.0'
  - name: ansible.eda
  - name: ansible.hub
  - name: ansible.platform
  - name: infra.aap_configuration
  - name: infra.controller_configuration
  - name: kubernetes.core
    version: '>=6.0.0'
