---
controller_credentials:
  - name: Linode machine
    credential_type: Machine
    organization: Default
    inputs:
      username: root
      password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        61303961366232343562656434633438616238333435326163336431393239646337366435623438
        3265643736653834393934333931333433613533343364620a633432326564366631613466373433
        66633237356263373866353937306362396130626666366434633035656630616238356665666234
        6637353835666139320a613033643239366631353231373533313663616362343531333133393933
        34326431323234633437613366366336613636336133623338666233366638323466
