---
controller_hosts:
  - name: loadtest-01
    inventory: linode-hosts
    variables:
      ansible_host: '139.177.207.183'

  - name: loadtest-02
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.201.30'

  - name: loadtest-03
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.196.103'

  - name: loadtest-04
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.196.129'

  - name: loadtest-05
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.196.96'

  - name: loadtest-06
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.28'

  - name: loadtest-07
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.29'

  - name: loadtest-08
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.88'

  - name: loadtest-09
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.229'

  - name: loadtest-10
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.21'
