---
controller_hosts:
  - name: loadtest-01
    enabled: true
    inventory: linode-hosts
    variables:
      ansible_host: '139.177.207.183'

  - name: loadtest-02
    enabled: true
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.201.30'

  - name: loadtest-03
    enabled: true
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.196.103'

  - name: loadtest-04
    enabled: false
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.196.129'

  - name: loadtest-05
    enabled: true
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.196.96'

  - name: loadtest-06
    enabled: true
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.28'

  - name: loadtest-07
    enabled: true
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.29'

  - name: loadtest-08
    enabled: true
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.88'

  - name: loadtest-09
    enabled: true
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.229'

  - name: loadtest-10
    enabled: true
    inventory: linode-hosts
    variables:
      ansible_host: '45.79.219.21'
