---
controller_templates:
  - name: Ping hosts
    allow_simultaneous: true
    credentials:
      - Linode machine
    inventory: linode-hosts
    job_slice_count: 9
    playbook: playbooks/ping.yml
    project: aap-operator-automation
