apiVersion: v1
kind: Secret
metadata:
  name: mario-hub-postgres-configuration
  namespace: aap-mario
data:
  host: MTkyLjE2OC4xLjU4
  port: NTQxNw==
  database: aHVi
  username: cG9zdGdyZXM=
  password: ZXhhbXBsZQ==
  sslmode: cHJlZmVy
  type: dW5tYW5hZ2Vk
type: Opaque
