apiVersion: v1
kind: Secret
metadata:
  name: bowser-hub-postgres-configuration
  namespace: aap-bowser
data:
  host: MTkyLjE2OC4xLjU4
  port: NTQxNQ==
  database: aHVi
  username: cG9zdGdyZXM=
  password: ZXhhbXBsZQ==
  sslmode: cHJlZmVy
  type: dW5tYW5hZ2Vk
type: Opaque
